# Generated by Django 2.1.5 on 2019-01-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BareboneShop', '0002_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
