# Generated by Django 2.1.5 on 2019-01-13 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Barebones', '0002_auto_20190113_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('product_cnt', models.IntegerField(default=0)),
                ('checked_out', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='products',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shopcart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='shopcart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
        migrations.DeleteModel(
            name='ShopCart',
        ),
    ]
